#!/bin/bash

PREFIX=/opt/monolith
export PATH=$PREFIX/bin:$PATH
export LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH

echo 'Entering monolithified shell.'
echo ''
mono --version | grep ^Mono
mcs --version

bash
